// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzoTI7aEQzN3qUH0L1KUNccHuKhjN1WBU',
    appId: '1:33648832268:web:c8dfed6aa64bef0bcfe329',
    messagingSenderId: '33648832268',
    projectId: 'christmasmooood',
    authDomain: 'christmasmooood.firebaseapp.com',
    storageBucket: 'christmasmooood.appspot.com',
    measurementId: 'G-ZVZJH2TMWL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8zWImI7_xeeebbw_myEoWsVcuGavd9O0',
    appId: '1:33648832268:android:fc637dcdf677efd2cfe329',
    messagingSenderId: '33648832268',
    projectId: 'christmasmooood',
    storageBucket: 'christmasmooood.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCd7zxQPLuiIWmMT6nMYDbLy2Mcw7CnCaM',
    appId: '1:33648832268:ios:e5054e95eb25ecd5cfe329',
    messagingSenderId: '33648832268',
    projectId: 'christmasmooood',
    storageBucket: 'christmasmooood.appspot.com',
    iosClientId: '33648832268-sfvttgjc2um6qdqepamu1gf0jb8v7bj1.apps.googleusercontent.com',
    iosBundleId: 'com.example.christmasspa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCd7zxQPLuiIWmMT6nMYDbLy2Mcw7CnCaM',
    appId: '1:33648832268:ios:e5054e95eb25ecd5cfe329',
    messagingSenderId: '33648832268',
    projectId: 'christmasmooood',
    storageBucket: 'christmasmooood.appspot.com',
    iosClientId: '33648832268-sfvttgjc2um6qdqepamu1gf0jb8v7bj1.apps.googleusercontent.com',
    iosBundleId: 'com.example.christmasspa',
  );
}
